FROM xamoc/python2

RUN pip install \
    python-openstackclient \
    python-novaclient \
    python-glanceclient \
    python-cinderclient \
    python-keystoneclient \
    python-neutronclient \
    python-swiftclient \
    python-heatclient
